spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: Manas@65
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: ORDER-SERVICE

  eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-with-registry: true
server:
  port: 8084
app:
  expirationTime: 604800000
  jwt-secret: e58b1787cf04010493fe722e9129e1e4c9876b91ddb67683dcf28d87d467cc1a